### ISSUE TITLE
vale roll out

### ISSUE THREAD

**Issue by edmundmiller** [nf-core/ops#31]
I'll migrate this over once we create the repo...

```[tasklist]
### Tasks

- [ ] Roll out a few specific repos first
- [ ] Tools
- [ ] Website(https://github.com/nf-core/website/pull/2236)
- [ ] Modules
- [ ] Pipeline template
- [ ] Make a config (https://github.com/nf-core/website/pull/2285)
- [ ] Borrow from Seqera config
- [ ] Rope in Seqera Devrel for Prose settings

```

**Comment by edmundmiller** [comment]
Inspiration: https://github.com/search?utf8=%E2%9C%93&q=path%3A.vale.ini+Path+https&type=code

**Comment by edmundmiller** [comment]
@mashehu I think this is the issue https://github.com/errata-ai/vale-action/issues/103
